[tool.poetry]
name = "spurchart"
version = "0.0.25"
description = "Spur charts for super-heterodyne mixers, DACs, and ADCs"
authors = ["Justin Magers <magers@ieee.org>"]

[tool.poetry.dependencies]
python = ">=3.9,<=3.14"
pandas = "^2.1.2"
scipy = "^1.8.0"
matplotlib = "^3.5.2"
scikit-rf = "^1.8.0"
colorcet = "^3.0.1"
bokeh = "^3.1.0"

[tool.poetry.group.dev.dependencies]
ipykernel = "^6.23.1"

[tool.poetry.group.doc.dependencies]
schemdraw = {extras = ["matplotlib", "svgmath"], version = "^0.16"}
mkdocs-material = "^9.1.14"
mkdocstrings = {extras = ["python"], version = "^0.21.2"}
mkdocs-gen-files = "^0.5.0"
mkdocs-literate-nav = "^0.6.0"
mkdocs-section-index = "^0.3.5"

[tool.poetry.group.test.dependencies]
pytest = "^7.4.3"

[tool.black]
line-length = 100

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
